name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Installing Dependencies
        run: npm install
      - name: Building App to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
